// Generated by hand from supabase/schema.sql — regenerate with the
// Supabase CLI once the project is linked to keep this in sync:
//   npx supabase gen types typescript --project-id <ref> > types/database.types.ts
//
// Table names are kebab-case, so access them as string literals, e.g.
// supabase.from("miembros-equipo"), not dot notation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      equipos: {
        Row: {
          id: string;
          nombre: string;
          escudo_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          escudo_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          escudo_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      "miembros-equipo": {
        Row: {
          id: string;
          equipo_id: string;
          user_id: string;
          rol: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          user_id: string;
          rol: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          user_id?: string;
          rol?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "miembros-equipo_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      rivales: {
        Row: {
          id: string;
          equipo_id: string;
          nombre: string;
          notas: string | null;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          nombre: string;
          notas?: string | null;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          nombre?: string;
          notas?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "rivales_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      ejercicios: {
        Row: {
          id: string;
          equipo_id: string;
          titulo: string;
          categoria: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          titulo: string;
          categoria: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          titulo?: string;
          categoria?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ejercicios_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      "pasos-ejercicio": {
        Row: {
          id: string;
          ejercicio_id: string;
          orden: number;
          descripcion: string;
        };
        Insert: {
          id?: string;
          ejercicio_id: string;
          orden: number;
          descripcion: string;
        };
        Update: {
          id?: string;
          ejercicio_id?: string;
          orden?: number;
          descripcion?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pasos-ejercicio_ejercicio_id_fkey";
            columns: ["ejercicio_id"];
            isOneToOne: false;
            referencedRelation: "ejercicios";
            referencedColumns: ["id"];
          },
        ];
      };
      entrenamientos: {
        Row: {
          id: string;
          equipo_id: string;
          titulo: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          titulo: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          titulo?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "entrenamientos_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      "entrenamientos-ejercicios": {
        Row: {
          id: string;
          entrenamiento_id: string;
          ejercicio_id: string;
          orden: number;
        };
        Insert: {
          id?: string;
          entrenamiento_id: string;
          ejercicio_id: string;
          orden: number;
        };
        Update: {
          id?: string;
          entrenamiento_id?: string;
          ejercicio_id?: string;
          orden?: number;
        };
        Relationships: [
          {
            foreignKeyName: "entrenamientos-ejercicios_entrenamiento_id_fkey";
            columns: ["entrenamiento_id"];
            isOneToOne: false;
            referencedRelation: "entrenamientos";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "entrenamientos-ejercicios_ejercicio_id_fkey";
            columns: ["ejercicio_id"];
            isOneToOne: false;
            referencedRelation: "ejercicios";
            referencedColumns: ["id"];
          },
        ];
      };
      jugadoras: {
        Row: {
          id: string;
          equipo_id: string;
          nombre: string;
          dorsal: number | null;
          posicion: string | null;
          minutos_jugados: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          nombre: string;
          dorsal?: number | null;
          posicion?: string | null;
          minutos_jugados?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          nombre?: string;
          dorsal?: number | null;
          posicion?: string | null;
          minutos_jugados?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "jugadoras_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      asistencia: {
        Row: {
          id: string;
          jugadora_id: string;
          fecha: string;
          estado: string;
        };
        Insert: {
          id?: string;
          jugadora_id: string;
          fecha: string;
          estado: string;
        };
        Update: {
          id?: string;
          jugadora_id?: string;
          fecha?: string;
          estado?: string;
        };
        Relationships: [
          {
            foreignKeyName: "asistencia_jugadora_id_fkey";
            columns: ["jugadora_id"];
            isOneToOne: false;
            referencedRelation: "jugadoras";
            referencedColumns: ["id"];
          },
        ];
      };
      torneos: {
        Row: {
          id: string;
          equipo_id: string;
          division: string;
          periodo: string;
          anio: number;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          division: string;
          periodo: string;
          anio: number;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          division?: string;
          periodo?: string;
          anio?: number;
        };
        Relationships: [
          {
            foreignKeyName: "torneos_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      partidos: {
        Row: {
          id: string;
          equipo_id: string;
          rival_id: string | null;
          torneo_id: string | null;
          fecha: string;
          hora: string | null;
          cancha: string | null;
          estado: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          rival_id?: string | null;
          torneo_id?: string | null;
          fecha: string;
          hora?: string | null;
          cancha?: string | null;
          estado?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          rival_id?: string | null;
          torneo_id?: string | null;
          fecha?: string;
          hora?: string | null;
          cancha?: string | null;
          estado?: string;
        };
        Relationships: [
          {
            foreignKeyName: "partidos_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "partidos_rival_id_fkey";
            columns: ["rival_id"];
            isOneToOne: false;
            referencedRelation: "rivales";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "partidos_torneo_id_fkey";
            columns: ["torneo_id"];
            isOneToOne: false;
            referencedRelation: "torneos";
            referencedColumns: ["id"];
          },
        ];
      };
      "resultados-partidos": {
        Row: {
          id: string;
          partido_id: string;
          goles_favor: number;
          goles_contra: number;
        };
        Insert: {
          id?: string;
          partido_id: string;
          goles_favor?: number;
          goles_contra?: number;
        };
        Update: {
          id?: string;
          partido_id?: string;
          goles_favor?: number;
          goles_contra?: number;
        };
        Relationships: [
          {
            foreignKeyName: "resultados-partidos_partido_id_fkey";
            columns: ["partido_id"];
            isOneToOne: true;
            referencedRelation: "partidos";
            referencedColumns: ["id"];
          },
        ];
      };
      "participacion-partidos": {
        Row: {
          id: string;
          partido_id: string;
          jugadora_id: string;
          convocada: boolean;
          jugo: boolean;
          minutos_jugados: number;
        };
        Insert: {
          id?: string;
          partido_id: string;
          jugadora_id: string;
          convocada?: boolean;
          jugo?: boolean;
          minutos_jugados?: number;
        };
        Update: {
          id?: string;
          partido_id?: string;
          jugadora_id?: string;
          convocada?: boolean;
          jugo?: boolean;
          minutos_jugados?: number;
        };
        Relationships: [
          {
            foreignKeyName: "participacion-partidos_partido_id_fkey";
            columns: ["partido_id"];
            isOneToOne: false;
            referencedRelation: "partidos";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "participacion-partidos_jugadora_id_fkey";
            columns: ["jugadora_id"];
            isOneToOne: false;
            referencedRelation: "jugadoras";
            referencedColumns: ["id"];
          },
        ];
      };
      formaciones: {
        Row: {
          id: string;
          equipo_id: string;
          nombre: string | null;
          esquema: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          equipo_id: string;
          nombre?: string | null;
          esquema: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          equipo_id?: string;
          nombre?: string | null;
          esquema?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "formaciones_equipo_id_fkey";
            columns: ["equipo_id"];
            isOneToOne: false;
            referencedRelation: "equipos";
            referencedColumns: ["id"];
          },
        ];
      };
      "formaciones-jugadoras": {
        Row: {
          id: string;
          formacion_id: string;
          jugadora_id: string;
          posicion_x: number | null;
          posicion_y: number | null;
          titular: boolean;
          orden_suplente: number | null;
        };
        Insert: {
          id?: string;
          formacion_id: string;
          jugadora_id: string;
          posicion_x?: number | null;
          posicion_y?: number | null;
          titular?: boolean;
          orden_suplente?: number | null;
        };
        Update: {
          id?: string;
          formacion_id?: string;
          jugadora_id?: string;
          posicion_x?: number | null;
          posicion_y?: number | null;
          titular?: boolean;
          orden_suplente?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "formaciones-jugadoras_formacion_id_fkey";
            columns: ["formacion_id"];
            isOneToOne: false;
            referencedRelation: "formaciones";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "formaciones-jugadoras_jugadora_id_fkey";
            columns: ["jugadora_id"];
            isOneToOne: false;
            referencedRelation: "jugadoras";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      es_miembro: {
        Args: { equipo: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

type PublicSchema = Database["public"];

export type Tables<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Row"];

export type TablesInsert<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Insert"];

export type TablesUpdate<
  T extends keyof PublicSchema["Tables"],
> = PublicSchema["Tables"][T]["Update"];
